#!/usr/bin/env python3
import argparse,hashlib,json
from pathlib import Path
H=Path(__file__).resolve().parent;M=json.loads((H/'manifest.json').read_text())
FROZEN=['PROTOCOL.md','STOP_GATES.md','manifest.json','tasks.json','goldens/goldens.jsonl','runner.py','scorer.py','audit.py']
def freeze_text():return '\n'.join(f'{hashlib.sha256((H/p).read_bytes()).hexdigest()}  {p}' for p in FROZEN)+'\n'
def div(a,b):return a/b if b else 1.0
def audit(data):
 sess=[(r,x) for r in data['rows'] for x in r['sessions']];tmf=[(r,x) for r,x in sess if r['arm']=='TMF_INJECT_ONLY'];sem=[x for _,x in tmf if x['phase']=='semantic_mutation'];fresh=[x for _,x in tmf if x['phase'] in ('fresh_revisit','unrelated_mutation')];unknown=[x for _,x in tmf if x['phase']=='unknown_region']
 predicted=sum(x['middleware_kind']=='STALE' for x in sem);actual=len(sem);tp=sum(x['middleware_kind']=='STALE' for x in sem)
 mech={'valid_sequences':len({r['sequence'] for r,_ in tmf if len(r['independent_session_ids'])==len(set(r['independent_session_ids']))==5}),'stale_precision':div(tp,predicted),'stale_recall':div(tp,actual),'false_inject':sum(x['middleware_kind']=='FRESH' for x in unknown),'stale_trust_errors':sum(x['stale_trust_error'] for x in sem),'unknown_false_hits':sum(x['middleware_kind']!='MISS' for x in unknown),'localized_reread_rate':div(sum(x['localized_reread'] for x in sem),len(sem)),'fresh_claim_accuracy':div(sum(x['fresh_claim_hash_matches'] for x in fresh),len(fresh)),'pre_read_order_errors':sum(not x['injection_before_first_read'] for _,x in tmf if x['phase']!='first_visit'),'budget_errors':sum(x['injection_items']>M['budget']['injection_top_k'] or x['injection_tokens']>M['budget']['injection_max_tokens'] for _,x in tmf),'old_fact_leaks':sum(not x['old_fact_withheld'] for x in sem),'independent_session_errors':sum(len(r['independent_session_ids'])!=len(set(r['independent_session_ids'])) for r in data['rows'])}
 by={(r['sequence'],r['arm'],x['phase']):x for r,x in sess};savings={k:sum(by[(s,k,'fresh_revisit')][m] for s in {r['sequence'] for r in data['rows']}) for k in M['arms'] for m in []}
 seqs=sorted({r['sequence'] for r in data['rows']});source=sum(by[(s,'SOURCE_ONLY','fresh_revisit')]['source_lines'] for s in seqs);tmfl=sum(by[(s,'TMF_INJECT_ONLY','fresh_revisit')]['source_lines'] for s in seqs);sr=sum(by[(s,'SOURCE_ONLY','fresh_revisit')]['read_calls'] for s in seqs);tr=sum(by[(s,'TMF_INJECT_ONLY','fresh_revisit')]['read_calls'] for s in seqs);st=sum(by[(s,'SOURCE_ONLY','fresh_revisit')]['total_tokens'] for s in seqs);tt=sum(by[(s,'TMF_INJECT_ONLY','fresh_revisit')]['total_tokens'] for s in seqs)
 freshsave={'source_lines':{'source_only':source,'tmf':tmfl,'delta':tmfl-source},'read_calls':{'source_only':sr,'tmf':tr,'delta':tr-sr},'total_tokens':{'source_only':st,'tmf':tt,'delta':tt-st},'directional_pass':tmfl<source or tr<sr or tt<st}
 outcome={arm:{'n':len(xs),'task_accuracy':div(sum(x['correct'] for x in xs),len(xs)),'citation_accuracy':div(sum(x['citation_ok'] for x in xs),len(xs)),'source_lines':sum(x['source_lines'] for x in xs),'source_bytes':sum(x['source_bytes'] for x in xs),'read_calls':sum(x['read_calls'] for x in xs),'prompt_tokens':sum(x['prompt_tokens'] for x in xs),'completion_tokens':sum(x['completion_tokens'] for x in xs),'injection_tokens':sum(x['injection_tokens'] for x in xs),'total_tokens':sum(x['total_tokens'] for x in xs),'latency_seconds':sum(x['latency_seconds'] for x in xs),'attribution_counts':{a:sum(x['machine_attribution']==a for x in xs) for a in sorted({x['machine_attribution'] for x in xs})}} for arm in M['arms'] for xs in [[x for r,x in sess if r['arm']==arm]]}
 passm=mech['stale_precision']==1 and mech['stale_recall']==1 and all(mech[k]==0 for k in ['false_inject','stale_trust_errors','unknown_false_hits','pre_read_order_errors','budget_errors','old_fact_leaks','independent_session_errors']) and mech['localized_reread_rate']==1 and mech['fresh_claim_accuracy']==1
 return {'mechanism':mech,'mechanism_pass':passm,'fresh_savings':freshsave,'value_gate_pass':freshsave['directional_pass'],'agent_outcome':outcome}
def main():
 a=argparse.ArgumentParser();a.add_argument('run');a.add_argument('--freeze',action='store_true');x=a.parse_args()
 if x.freeze:(H/'FROZEN.sha256').write_text(freeze_text());return
 expected=(H/'FROZEN.sha256').read_text();assert expected==freeze_text(),'frozen files changed'
 p=Path(x.run);report=audit(json.loads(p.read_text()));out=p.with_suffix('.audit.json');out.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');md=p.with_suffix('.audit.md');md.write_text('# Layered audit\n\n```json\n'+json.dumps(report,indent=2,sort_keys=True)+'\n```\n');print(out);raise SystemExit(0 if report['mechanism_pass'] else 2)
if __name__=='__main__':main()
