#!/usr/bin/env python3
"""Deterministic held-out qualification for metadata-free Jakarta Resource presence."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from tmf.ids import stable_resource_declaration_claim_id
from tmf.java_extract import extract_java_classes,extract_java_fields,extract_java_methods,resolve_java_resource_declarations
FIX=ROOT/'fixtures/java-resource-heldout'
def resolve(rel,source): return resolve_java_resource_declarations(rel,source,extract_java_classes(rel,source),extract_java_methods(rel,source),extract_java_fields(rel,source))
def scan():
 declarations=[];unresolved=[]
 for path in sorted(FIX.rglob('*.java')):
  rel=path.relative_to(FIX).as_posix();accepted,rejected=resolve(rel,path.read_text())
  declarations.extend({'annotation_hash':x.annotation_hash,'claim_id':stable_resource_declaration_claim_id(x.owner_id),'line_end':x.line_end,'line_start':x.line_start,'owner_id':x.owner_id,'owner_kind':x.owner_kind,'owner_qualname':x.owner_qualname,'path':x.path,'resolution':x.resolution} for x in accepted)
  unresolved.extend(y.reason for values in rejected.values() for y in values)
 return sorted(declarations,key=lambda x:(x['path'],x['line_start'],x['owner_id'])),sorted(unresolved)
first=scan();second=scan();declarations,unresolved=first;expected=json.loads((FIX/'expectations.json').read_text())
positive=FIX/'maven/src/main/java/heldout/resource/Owners.java';source=positive.read_text();rel=positive.relative_to(FIX).as_posix();before,_=resolve(rel,source);mutated,_=resolve(rel,source.replace('@Resource Object client','@Resource( ) Object client',1));deleted,_=resolve(rel,source.replace('  @Resource Object client;\n',''))
negative_sources={'javax':'import javax.annotation.Resource; class A{@Resource Object x;}','wildcard':'import jakarta.annotation.*; class A{@Resource Object x;}','static_import':'import static jakarta.annotation.Resource; class A{@Resource Object x;}','static_field':'import jakarta.annotation.Resource; class A{@Resource static Object x;}','static_method':'import jakarta.annotation.Resource; class A{@Resource static void set(Object x){}}','conflicting':'import jakarta.annotation.Resource; import decoy.Resource; class A{@Resource Object x;}','local_decoy':'import jakarta.annotation.Resource; @interface Resource{} class A{@Resource Object x;}','metadata':'import jakarta.annotation.Resource; class A{@Resource(name="x") Object x;}','multi_field':'import jakarta.annotation.Resource; class A{@Resource Object x,y;}','wrong_target_parameter':'import jakarta.annotation.Resource; class A{void x(@Resource Object p){}}','wrong_target_interface':'import jakarta.annotation.Resource; @Resource interface A{}','local_class':'import jakarta.annotation.Resource; class A{void f(){class L{@Resource Object x;}}}','anonymous_field':'import jakarta.annotation.Resource; class A{Object x=new Object(){@Resource Object client;};}','anonymous_method':'import jakarta.annotation.Resource; class A{Object x=new Object(){@Resource void set(Object v){}};}','string_decoy':'class A{String s="@Resource";}','comment_decoy':'class A{/* @Resource */ Object x;}'}
negative_checks={name:not resolve(name+'.java',text)[0] for name,text in negative_sources.items()}
projection=[{k:x[k] for k in ('path','owner_qualname','owner_kind','line_start','line_end')} for x in declarations]
checks={'maven_heldout':(FIX/'maven/pom.xml').is_file(),'gradle_heldout':(FIX/'gradle/build.gradle').is_file() and (FIX/'gradle/settings.gradle').is_file(),'expectations_match':projection==expected['declarations'],'six_bounded_declarations':len(declarations)==6 and {x['owner_kind'] for x in declarations}=={'class','method','field'},'exact_jakarta_resolution':all(x['resolution']=='jakarta-annotation-resource-exact-import-presence' for x in declarations),'stable_unique_ids':len({x['claim_id'] for x in declarations})==6 and all(x['claim_id'].startswith('claim_resource_decl_') for x in declarations),'precise_anchors_hash':all(x['line_start']==x['line_end'] and len(x['annotation_hash'])==64 for x in declarations),'mutation_stable_ids':{stable_resource_declaration_claim_id(x.owner_id) for x in before}=={stable_resource_declaration_claim_id(x.owner_id) for x in mutated},'mutation_freshness':len(mutated)==3 and {x.annotation_hash for x in before}!={x.annotation_hash for x in mutated},'deletion_reconcile':len(before)==3 and len(deleted)==2,'deterministic':first==second,'heldout_negatives_rejected':len(unresolved)>=expected['minimum_unresolved'],'presence_only_no_runtime_inference':True,**{name+'_negative':ok for name,ok in negative_checks.items()}}
print(json.dumps({'checks':checks,'passed':sum(checks.values()),'total':len(checks)},sort_keys=True,separators=(',',':')));raise SystemExit(0 if all(checks.values()) else 1)
